"""A small, curated seed of well-documented historical market events.

These are widely-verifiable public facts (halving dates, official policy
actions, well-reported crashes) written by hand, not fetched from an API or
generated by an LLM -- consistent with this project's rule of never
fabricating data. This is a starting seed, not an exhaustive feed; extend
`SEED_EVENTS` as needed.
"""

from datetime import UTC, datetime

from sqlalchemy import select

from app.database.models import HistoricalEvent, HistoricalEventCategory

SEED_EVENTS: list[dict] = [
    {
        "event_date": datetime(2012, 11, 28, tzinfo=UTC),
        "title": "Bitcoin Halving #1",
        "category": HistoricalEventCategory.HALVING,
        "description": "Block reward drops from 50 to 25 BTC.",
        "symbols_affected": ["BTC"],
        "source": "manual_seed",
    },
    {
        "event_date": datetime(2016, 7, 9, tzinfo=UTC),
        "title": "Bitcoin Halving #2",
        "category": HistoricalEventCategory.HALVING,
        "description": "Block reward drops from 25 to 12.5 BTC.",
        "symbols_affected": ["BTC"],
        "source": "manual_seed",
    },
    {
        "event_date": datetime(2020, 3, 12, tzinfo=UTC),
        "title": "COVID-19 Crash ('Black Thursday')",
        "category": HistoricalEventCategory.CRASH,
        "description": (
            "Global markets and crypto crash together as COVID-19 lockdowns begin; "
            "BTC fell roughly 40% in a single day."
        ),
        "symbols_affected": ["BTC", "ETH", "SPX", "NASDAQ", "DJI", "VIX"],
        "source": "manual_seed",
    },
    {
        "event_date": datetime(2020, 5, 11, tzinfo=UTC),
        "title": "Bitcoin Halving #3",
        "category": HistoricalEventCategory.HALVING,
        "description": "Block reward drops from 12.5 to 6.25 BTC.",
        "symbols_affected": ["BTC"],
        "source": "manual_seed",
    },
    {
        "event_date": datetime(2022, 5, 9, tzinfo=UTC),
        "title": "TerraUSD (UST) De-peg / Collapse",
        "category": HistoricalEventCategory.CRASH,
        "description": (
            "Algorithmic stablecoin TerraUSD loses its USD peg, triggering a "
            "cascading collapse of the Terra/LUNA ecosystem and broad crypto selloff."
        ),
        "symbols_affected": ["BTC", "ETH"],
        "source": "manual_seed",
    },
    {
        "event_date": datetime(2022, 11, 11, tzinfo=UTC),
        "title": "FTX Collapse",
        "category": HistoricalEventCategory.BLACK_SWAN,
        "description": "FTX, then one of the largest crypto exchanges, files for bankruptcy.",
        "symbols_affected": ["BTC", "ETH"],
        "source": "manual_seed",
    },
    {
        "event_date": datetime(2023, 3, 10, tzinfo=UTC),
        "title": "Silicon Valley Bank Collapse",
        "category": HistoricalEventCategory.BLACK_SWAN,
        "description": (
            "SVB fails and is placed into FDIC receivership, the largest US bank "
            "failure since 2008; triggers a broader regional-banking crisis."
        ),
        "symbols_affected": ["SPX", "NASDAQ", "VIX", "BTC"],
        "source": "manual_seed",
    },
    {
        "event_date": datetime(2024, 1, 10, tzinfo=UTC),
        "title": "US Spot Bitcoin ETFs Approved",
        "category": HistoricalEventCategory.REGULATORY,
        "description": "The SEC approves the first US spot Bitcoin ETFs for listing and trading.",
        "symbols_affected": ["BTC"],
        "source": "manual_seed",
    },
    {
        "event_date": datetime(2024, 4, 20, tzinfo=UTC),
        "title": "Bitcoin Halving #4",
        "category": HistoricalEventCategory.HALVING,
        "description": "Block reward drops from 6.25 to 3.125 BTC.",
        "symbols_affected": ["BTC"],
        "source": "manual_seed",
    },
]


async def seed_events(session_factory) -> int:
    """Inserts any seed events not already present (matched by title + date). Idempotent."""
    async with session_factory() as session:
        existing = set(
            await session.execute(select(HistoricalEvent.title, HistoricalEvent.event_date))
        )
        inserted = 0
        for event in SEED_EVENTS:
            key = (event["title"], event["event_date"])
            if key in existing:
                continue
            session.add(HistoricalEvent(**event))
            inserted += 1
        await session.commit()
        return inserted
